[local]
localhost

[mongodb]
mongodb.manojkoney.store


[redis]
redis.manojkoney.store


[mysql]
mysql.manojkoney.store

[rabbitmq]
rabbitmq.manojkoney.store

[catalogue]
catalogue.manojkoney.store

[user]
user.manojkoney.store

[cart]
cart.manojkoney.store

[shipping]
shipping.manojkoney.store

[payment]
payment.manojkoney.store

[frontend]
frontend.manojkoney.store

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/Roboshop-Ansible-V2/Key.pem