
- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3
    - unzip
    - gcc
    - python3-dev
    - python3-pip


- name: application setup
  import_role:
    name: common
    tasks_from: app_setup

- name: Install dependencies from requirements.txt
  command: pip3 install -r /app/requirements.txt --break-system-packages --ignore-installed typing_extensions

- name: "copy {{ component }} service"
  import_role:
    name: common
    tasks_from: copy_service

- name: Restart service
  import_role:
    name: common
    tasks_from: service_restart