- name: Download NodeSource setup script
  get_url:
    url: https://deb.nodesource.com/setup_20.x
    dest: /tmp/nodesource_setup.sh
    mode: '0755'

- name: Run NodeSource setup script
  shell: bash /tmp/nodesource_setup.sh
  args:
    executable: /bin/bash

- name: Install nodejs
  apt:
    name: nodejs
    state: present

- name: Nodejs version
  command: node -v
  register: node_output

- name: Show nodejs version
  debug:
    var: node_output

- name: Install Node.js dependencies from app direc
  community.general.npm:
    path: /app
    state: present